{{- range $name, $agent := .Values.agents }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "agent-broker.fullname" $) $name | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "agent-broker.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  clusterIP: None
  selector:
    {{- include "agent-broker.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}
