{{- range $name, $cfg := .Values.agents }}
{{- if and (ne (include "openab.agentEnabled" $cfg) "false") ($cfg.gateway).enabled }}
{{- $gwCfg := omit $cfg "nameOverride" }}
{{- $d := dict "ctx" $ "agent" (printf "%s-gateway" $name) "cfg" $gwCfg }}
{{- $hasTeams := and (($cfg.gateway).teams).appId (($cfg.gateway).teams).appSecret }}
{{- if $hasTeams }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openab.agentFullname" $d }}
  labels:
    {{- include "openab.labels" $d | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  teams-app-secret: {{ ($cfg.gateway).teams.appSecret | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
