{{- if .Values.discord.botToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openab.fullname" . }}
  labels:
    {{- include "openab.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  discord-bot-token: {{ .Values.discord.botToken | b64enc | quote }}
{{- end }}
